# Generated by Django 4.2.5 on 2023-10-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSimulacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
