# Generated by Django 4.2.5 on 2023-10-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSimulacion', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
